export const GET_LIBRARY_REQUEST = "GET_LIBRARY_REQUEST";
export const GET_LIBRARY_SUCCESS = "GET_LIBRARY_SUCCESS";
export const GET_LIBRARY_ERROR = "GET_LIBRARY_ERROR";

export const CREATE_LIBRARY_REQUEST = "CREATE_LIBRARY_REQUEST";
export const CREATE_LIBRARY_SUCCESS = "CREATE_LIBRARY_SUCCESS";
export const CREATE_LIBRARY_ERROR = "CREATE_LIBRARY_ERROR";

export const INCREMENT_LIBRARY_REQUEST = "INCREMENT_LIBRARY_REQUEST";
export const INCREMENT_LIBRARY_SUCCESS = "INCREMENT_LIBRARY_SUCCESS";
export const INCREMENT_LIBRARY_ERROR = "INCREMENT_LIBRARY_ERROR";
export const INCREMENT_LIBRARY_RESET = "INCREMENT_LIBRARY_RESET";

export const DECREMENT_LIBRARY_REQUEST = "DECREMENT_LIBRARY_REQUEST";
export const DECREMENT_LIBRARY_SUCCESS = "DECREMENT_LIBRARY_SUCCESS";
export const DECREMENT_LIBRARY_ERROR = "DECREMENT_LIBRARY_ERROR";
export const DECREMENT_LIBRARY_RESET = "DECREMENT_LIBRARY_RESET";
